---
title       : Developing Data Project
subtitle    : Project Write Up
author      : Azeem Iqbal
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## StopCalc  


### Introducing to you, StopCalc, a creative and innovative solution to society's most important problem.                            
                
                        
                                    
                                            

## How we can change your life

### StopCalc is an intuitive, well designed app designed with the revolutionary Shiny framework for R. It handles exceptionally complex calculations extremely quickly, and is even able to predict the future!

---

## Our trials so far

### We have been in the alpha phase for about 2 months now, since our inception we have been collecting data on hours of StopCalc used per day and happinesss levels as measured by dopamine levels in the brain. We have seen tremendously positive results, and there is a clear correlation between more StopCalc use and higher happiness levels.

---

```{r, echo=FALSE}
a = c(12,1,0,2,3,4,8,5,2,3,4,5,0,7,4,3,11,9,7,10,6,5,8,9)
b = c(99,20,10,20,40,30,80,60,30,40,10,20,30,60,20,50,90,95,55,65,60,80,50,75)
plot(a,b, xlab = 'Hours using StopCalc a day', ylab = 'Happiness (% of max Dopamine levels)', main = 'Happiness of trial users against daily hours of use')
c <- data.frame(a,b)
abline(lm(b ~ a, data = c))
```

---

## How it really works

### StopCalc may seem simple at first glance, however if you take a look under the hood you are able to see how incredibly sophisticated it really is. We have used cutting edge machine learning algorithms in order to provide the most accurate prediction possible. 
